class CanvasImgNames {
    static TABLE = "TABLE";
    static POSITION = "POSITION";
    static CARD_BACK_BLUE = "CARD_BACK_BLUE";

    static CARD_ACE_SPADES = "CARD_ACE_SPADES";
    static CARD_ACE_CLUBS = "CARD_ACE_CLUBS";
    static CARD_ACE_DIAMONDS = "CARD_ACE_DIAMONDS";
    static CARD_ACE_HEARTS = "CARD_ACE_HEARTS";

    static CARD_TWO_SPADES = "CARD_TWO_SPADES";
    static CARD_TWO_CLUBS = "CARD_TWO_CLUBS";
    static CARD_TWO_DIAMONDS = "CARD_TWO_DIAMONDS";
    static CARD_TWO_HEARTS = "CARD_TWO_HEARTS";

    static CARD_THREE_SPADES = "CARD_THREE_SPADES";
    static CARD_THREE_CLUBS = "CARD_THREE_CLUBS";
    static CARD_THREE_DIAMONDS = "CARD_THREE_DIAMONDS";
    static CARD_THREE_HEARTS = "CARD_THREE_HEARTS";

    static CARD_FOUR_SPADES = "CARD_FOUR_SPADES";
    static CARD_FOUR_CLUBS = "CARD_FOUR_CLUBS";
    static CARD_FOUR_DIAMONDS = "CARD_FOUR_DIAMONDS";
    static CARD_FOUR_HEARTS = "CARD_FOUR_HEARTS";

    static CARD_FIVE_SPADES = "CARD_FIVE_SPADES";
    static CARD_FIVE_CLUBS = "CARD_FIVE_CLUBS";
    static CARD_FIVE_DIAMONDS = "CARD_FIVE_DIAMONDS";
    static CARD_FIVE_HEARTS = "CARD_FIVE_HEARTS";

    static CARD_ACE_SPADES = "CARD_ACE_SPADES";
    static CARD_ACE_CLUBS = "CARD_ACE_CLUBS";
    static CARD_ACE_DIAMONDS = "CARD_ACE_DIAMONDS";
    static CARD_ACE_HEARTS = "CARD_ACE_HEARTS";

    static CARD_SIX_SPADES = "CARD_SIX_SPADES";
    static CARD_SIX_CLUBS = "CARD_SIX_CLUBS";
    static CARD_SIX_DIAMONDS = "CARD_SIX_DIAMONDS";
    static CARD_SIX_HEARTS = "CARD_SIX_HEARTS";

    static CARD_SEVEN_SPADES = "CARD_SEVEN_SPADES";
    static CARD_SEVEN_CLUBS = "CARD_SEVEN_CLUBS";
    static CARD_SEVEN_DIAMONDS = "CARD_SEVEN_DIAMONDS";
    static CARD_SEVEN_HEARTS = "CARD_SEVEN_HEARTS";

    static CARD_EIGHT_SPADES = "CARD_EIGHT_SPADES";
    static CARD_EIGHT_CLUBS = "CARD_EIGHT_CLUBS";
    static CARD_EIGHT_DIAMONDS = "CARD_EIGHT_DIAMONDS";
    static CARD_EIGHT_HEARTS = "CARD_EIGHT_HEARTS";

    static CARD_NINE_SPADES = "CARD_NINE_SPADES";
    static CARD_NINE_CLUBS = "CARD_NINE_CLUBS";
    static CARD_NINE_DIAMONDS = "CARD_NINE_DIAMONDS";
    static CARD_NINE_HEARTS = "CARD_NINE_HEARTS";

    static CARD_TEN_SPADES = "CARD_TEN_SPADES";
    static CARD_TEN_CLUBS = "CARD_TEN_CLUBS";
    static CARD_TEN_DIAMONDS = "CARD_TEN_DIAMONDS";
    static CARD_TEN_HEARTS = "CARD_TEN_HEARTS";

    static CARD_JACK_SPADES = "CARD_JACK_SPADES";
    static CARD_JACK_CLUBS = "CARD_JACK_CLUBS";
    static CARD_JACK_DIAMONDS = "CARD_JACK_DIAMONDS";
    static CARD_JACK_HEARTS = "CARD_JACK_HEARTS";

    static CARD_QUEEN_SPADES = "CARD_QUEEN_SPADES";
    static CARD_QUEEN_CLUBS = "CARD_QUEEN_CLUBS";
    static CARD_QUEEN_DIAMONDS = "CARD_QUEEN_DIAMONDS";
    static CARD_QUEEN_HEARTS = "CARD_QUEEN_HEARTS";

    static CARD_KING_SPADES = "CARD_KING_SPADES";
    static CARD_KING_CLUBS = "CARD_KING_CLUBS";
    static CARD_KING_DIAMONDS = "CARD_KING_DIAMONDS";
    static CARD_KING_HEARTS = "CARD_KING_HEARTS";

    static TOKEN1 = "TOKEN1";
    static TOKEN10 = "TOKEN10";
    static TOKEN50 = "TOKEN50";
    static TOKEN100 = "TOKEN100";
    static TOKEN200 = "TOKEN200";
    static TOKEN500 = "TOKEN500";

    static ARROW = "ARROW";
}


export default CanvasImgNames;