package com.blackjack.server.Game_Computer;

public enum CustomAssertions {
    PLAYER1_HAD_BJ_FROM_FIRST_HAND,
    PLAYER2_HAD_BJ_FROM_FIRST_HAND,
    PLAYER3_HAD_BJ_FROM_FIRST_HAND,
    PLAYER4_HAD_BJ_FROM_FIRST_HAND,
    PLAYER5_HAD_BJ_FROM_FIRST_HAND,
    PLAYER6_HAD_BJ_FROM_FIRST_HAND,
    DEALER_HAD_BJ_FROM_FIRST_HAND,
    PLAYER1_DID_NOT_HAVE_BJ_FROM_FIRST_HAND,
    PLAYER2_DID_NOT_HAVE_BJ_FROM_FIRST_HAND,
    PLAYER3_DID_NOT_HAVE_BJ_FROM_FIRST_HAND,
    PLAYER4_DID_NOT_HAVE_BJ_FROM_FIRST_HAND,
    PLAYER5_DID_NOT_HAVE_BJ_FROM_FIRST_HAND,
    PLAYER6_DID_NOT_HAVE_BJ_FROM_FIRST_HAND,
    DEALER_DID_NOT_HAVE_BJ_FROM_FIRST_HAND
}
